CC = g++
STD = -std=c++11
CFLAGS = $(STD) -Wall -Wextra -Wpedantic
SOURCES = $(wildcard *.cpp)
INC_DIRS = .

$(MAIN): $(SOURCES) $(SOURCES:.cpp=.hpp)
	$(CC) $(CFLAGS) -c $(SOURCES) $(INC_DIRS:%=-I%)
	@$(MAKE) -s clean

.PHONY: clean

clean:
	rm -f *.o *.gch
